![RMIT logo](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlAppozhCGl50pjgEZu_tTmalWJi3TjpNwCg&s)
|Course|Foundations of Artificial Intelligence for STEM|
|-----|-------|
|Course Code|COSC2968/COSC3053|
|Lecturer(s)|Mr.Nhat-Quang Tran and Mrs.Anh Le Van|
|Full name - Student ID| Le Kim Quyen - s3983370<br>Ton Dat Toan - s4070286<br>Nguyen Hong Ha - s3979100<br>Huynh Bao Dang Khoa - s4045607<br>Nguyen Viet Ngan Anh - s4103086|

# Predicting the age of abalone

## 1. Introduction

*Write something here*

## 2. Data Exploration

### 2.1. Import and Functions
Installing and getting started with Terminal:
+ pip install matplotlib
+ pip install seaborn
+ pip install ydata-profiling
+ pip install ipywidgets

To install the necessary libraries such as matplotlib [ref], seaborn [ref] and ydata [ref].

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport

### 2.2. Load the dataset

In [2]:
abalone_df = pd.read_csv('abalone.csv')
abalone_df.head() # Shows the first five samples

,Type,LongestShell,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

*Write something based on this format:*

**Catagorical Feature:**
+ `Type`: Type of abalones (M = male, F = female and I = infant)

**Numerical Features:**
+ `Length`: Longest shell measurement in mm (continuous)
+ `Diameter`: Perpendicular to length in mm (continuous)
+ `Height`: with meat in shell in mm (continuous)
+ `Whole weight`: whole abalone in g (continuous)
+ `Shucked weight`: weight of meat in g (continuous)
+ `Viscera weight`: gut weight (after bleeding) in g (continuous)
+ `Shell weight`: after being dried in g (continuous)
+ `Rings`: +1.5 gives the age in years (discrete)

In [3]:
abalone_df.info() # Shows overview of each feature

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Type           4177 non-null   object
 1   LongestShell   4177 non-null   float64
 2   Diameter       4177 non-null   float64
 3   Height         4177 non-null   float64
 4   WholeWeight    4177 non-null   float64
 5   ShuckedWeight  4177 non-null   float64
 6   VisceraWeight  4177 non-null   float64
 7   ShellWeight    4177 non-null   float64
 8   Rings          4177 non-null   int64
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB

*Write something? Q - idk*

### 2.3. Descriptive statistic, visualizations and correlation analysis

**An overview using ydata** [ref]**:**

In [4]:
# An overview using ydata
ydata = ProfileReport(abalone_df, title = 'Abalone overview')
ydata.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

*Write something? Q - idk*

**Scatter plot between every pair of feature using seaborn** [ref]**:**

In [5]:
# An overview of the relationship between each pair feature
sns.set_theme() # set default theme for plot

# Plot features with each color for each type of abalone, including male (M), female (F) and infant (I)
abalone_pp = sns.pairplot(data = abalone_df, hue = 'Type', corner = True, palette = 'Set2');

*Write something? Q - idk*

**Compute correlations between features**

In [6]:
# The variable contains correlations between features
abalone_corr = abalone_df.corr(numeric_only = True)
# abalone_corr

**Visualize using headmap from seaborn** [ref]**:**

In [7]:
ones_corr = np.ones_like(abalone_corr, dtype = bool) # create a matrix contains boolean values with the same shape as abalone_corr
mask = np.triu(ones_corr) # a mask contains half triangle matrix of True and False

# Remove redundant the first row and the last column
adjusted_abalone_corr = abalone_corr.iloc[1:, :-1]
adjusted_mask_corr = mask[1:, :-1]

# Create plot
fig, ax = plt.subplots(figsize = (10, 8))

# Show heatmap
sns.heatmap(data = adjusted_abalone_corr, mask = adjusted_mask_corr, cmap = 'Blues',
            annot = True, fmt = '.2f', vmin = -1, vmax = 1,
            linecolor = 'white', linewidths = .5, annot_kws = {'fontsize': 14});

*Write something? Q - idk*

### 2.4. Discover the data to gain insights

**Distribution of Numerical feature values**

In [8]:
abalone_df.describe()

,LongestShell,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

*Write something? Q - idk*

**Distribution of Categorical feature values**

In [9]:
abalone_df.describe(include = 'object')

        Type
count   4177
unique     3
top        M
freq    1528

*Write something? Q - idk*

**The relationship of diameter and height using jointplot from seaborn** [ref]**:**

In [10]:
sns.jointplot(data = abalone_df, x = 'Diameter', y = 'Height', hue = 'Type');

*Write something? Q - idk*

**The relationship of diameter and height using FacetGrid from seaborn** [ref]**:**

In [11]:
abalone_fg = sns.FacetGrid(data = abalone_df, col = 'Type')
abalone_fg.map(sns.scatterplot, 'Diameter', 'Height', alpha = .4);

*Write something? Q - idk*

**The relationship of diameter and rings using FaceGrid from seaborn** [ref]**:**

In [12]:
abalone_fg = sns.FacetGrid(data = abalone_df, col = 'Type')
abalone_fg.map(sns.scatterplot, 'Diameter', 'Rings', alpha = .4);

*Write something? Q - idk*

## 3. Data Preprocessing

### 3.1. Handle missing values
There is no missing values to handle?? 😢

In [13]:
# Calculate the percentage of missing values in each feature
for col in abalone_df.columns:
    missing_values = abalone_df[col].isna().sum() # Count the number of missing values
    print(f'Feature {col} has {missing_values / len(abalone_df) * 100}% missing values')

Feature Type has 0.0% missing values
Feature LongestShell has 0.0% missing values
Feature Diameter has 0.0% missing values
Feature Height has 0.0% missing values
Feature WholeWeight has 0.0% missing values
Feature ShuckedWeight has 0.0% missing values
Feature VisceraWeight has 0.0% missing values
Feature ShellWeight has 0.0% missing values
Feature Rings has 0.0% missing values

### 3.2. Identify and handle outliers
*Work here*

### 3.3. Separate labels from data
Choosing "Rings" column as tha label.

In [14]:
abalone_set_labels = abalone_df['Rings'].copy()
abalone_set = abalone_df.drop(columns = 'Rings')

abalone_set.head(), abalone_set_labels.head()

(  Type  LongestShell  Diameter  Height  WholeWeight  ShuckedWeight  \
 0    M         0.455     0.365   0.095       0.5140         0.2245
 1    M         0.350     0.265   0.090       0.2255         0.0995
 2    F         0.530     0.420   0.135       0.6770         0.2565
 3    M         0.440     0.365   0.125       0.5160         0.2155
 4    I         0.330     0.255   0.080       0.2050         0.0895

    VisceraWeight  ShellWeight
 0         0.1010        0.150
 1         0.0485        0.070
 2         0.1415        0.210
 3         0.1140        0.155
 4         0.0395        0.055  ,
 0    15
 1     7
 2     9
 3    10
 4     7
 Name: Rings, dtype: int64)

### 3.4. Encode categorical features
There is one categorical feature in the dataset need to be encoded: `Type`

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Create a class for encode columns
colTrans = ColumnTransformer(transformers = [('encode', OneHotEncoder(), [0])], remainder = 'passthrough')

# Encode
abalone_set = colTrans.fit_transform(abalone_set)
abalone_set, abalone_set.shape

(array([[0.    , 0.    , 1.    , ..., 0.2245, 0.101 , 0.15  ],
        [0.    , 0.    , 1.    , ..., 0.0995, 0.0485, 0.07  ],
        [1.    , 0.    , 0.    , ..., 0.2565, 0.1415, 0.21  ],
        ...,
        [0.    , 0.    , 1.    , ..., 0.5255, 0.2875, 0.308 ],
        [1.    , 0.    , 0.    , ..., 0.531 , 0.261 , 0.296 ],
        [0.    , 0.    , 1.    , ..., 0.9455, 0.3765, 0.495 ]]),
 (4177, 10))

In [16]:
# Transform abalone_set_labels into the same format with abalone_set
abalone_set_labels = abalone_set_labels.values
abalone_set_labels, abalone_set_labels.shape

(array([15,  7,  9, ...,  9, 10, 12]), (4177,))

### 3.5. Split the dataset
*Work here*

In [17]:
from sklearn.model_selection import train_test_split

# Split train_set, train_set_labels for training - test_set and test_set_labels for testing
train_set, test_set, train_set_labels, test_set_labels = train_test_split(abalone_set, abalone_set_labels, test_size = 0.2, random_state = 25)

### 3.6. Feature scaling
Scale features to zero mean and unit variance.

In [23]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

train_set[:, 3:] = std_scaler.fit_transform(train_set[:, 3:]) # just only scale numerical features, not category feature
test_set[:, 3:] = std_scaler.transform(test_set[:, 3:])

## 4. Model Training and Evaluation

**Note:**
+ `train_set` contains set data for training
+ `train_set_labels` contains labels for training
+ `test_set` contains set data for testing
+ `test_set_labels` contains labels for testing

**Modules in lec:**
+ LinearRegression
+ DecisionTreeRegressor
+ RandomForestRegressor
+ PolynomialFeatures